name: Canducci Hub Dev

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-test-pack-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Testes
        run: dotnet test Canducci.HubDev.Tests/Canducci.HubDev.Tests.csproj --configuration Release --no-build

      - name: Empacotar pacotes
        run: |
          dotnet pack Canducci.HubDev/Canducci.HubDev.csproj --configuration Release --no-build -o ./nupkg
          dotnet pack Canducci.HubDev.Web/Canducci.HubDev.Web.csproj --configuration Release --no-build -o ./nupkg

      - name: Publicar no NuGet
        shell: pwsh
        run: |
            $packages = Get-ChildItem -Path ./nupkg -Filter *.nupkg
            foreach ($pkg in $packages) {
                dotnet nuget push $pkg.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
            }
